# FROM node:24 AS base

# WORKDIR /frontend
# COPY package*.json ./
# RUN npm install

# COPY . .
# EXPOSE 3000
# CMD ["next", "dev", "-p", "3000"]

FROM node:24 AS base

WORKDIR /frontend

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
